http :
  routers :
    httpbin-router :
      entryPoints :
      - web
      rule : HostRegexp(`{name:.*}`)
      service : vets-service

  services :
    vets-service :
      loadBalancer :
        servers :
        - url  : "http://192.168.1.5:53979/"
